module.exports = {
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/node_modules/**',
    '!**/.storybook/**',
    '!**/tests/**',
    '!**/coverage/**',
    '!**/*.spec.{ts,tsx}',
    '!**/*.test.{ts,tsx}',
    '!**/*.stories.{ts,tsx}',
    '!**/*.config.{ts,tsx,js}',
    '!**/__mocks__/**',
    '!jest.config.js',
    '!next-env.d.ts',
    '!global.d.ts',
    '!enzyme.js',
    '!lint-staged.config.js',
    '!next.config.js',
    '!types/**',
    '!**/types/**',
    '!*.d.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 18,
      functions: 34,
      lines: 39,
      statements: 37,
    },
  },
  setupFiles: ['<rootDir>/enzyme.js'],
  preset: 'ts-jest',
  testPathIgnorePatterns: [
    '/.next/',
    '/node_modules/',
    '/lib/',
    '/tests/',
    '/coverage/',
    '/.storybook/',
    '/e2e/',
  ],
  testRegex: '(/__test__/.*|\\.(test|spec))\\.(ts|tsx|js)$',
  testURL: 'http://localhost',
  testEnvironment: 'jsdom',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json'],
  moduleNameMapper: {
    '\\.(css|less)$': '<rootDir>/__mocks__/styleMock.js',
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$':
      '<rootDir>/__mocks__/fileMock.js',
  },

  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': ['babel-jest', { presets: ['next/babel'] }],
  },
  transformIgnorePatterns: ['<rootDir>/node_modules/'],
};
